import http from "node:http";
const PORT=Number(process.env.PORT||3000);
const URLS=[
 "https://webgw.tse.ir/InstrumentProvider/api/v1/MarketWatch/MarketWatchOption/fa",
 "https://webgw.tse.ir/InstrumentProvider/api/v1/MarketWatch/MarketWatchTradeOption/fa"
];
const page=String.raw`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>داشبورد اختیار معامله</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#17202a;font-family:Tahoma,Arial,sans-serif}.wrap{max-width:1200px;margin:auto;padding:12px}.top,.card{background:#fff;border-radius:16px;padding:14px;margin-bottom:12px}.top{background:#17202a;color:#fff}h1{font-size:21px;margin:0 0 8px}h2,h3{margin:4px 0 12px}.sub,.note{font-size:12px;line-height:1.9;opacity:.85}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.badge,button{border:0;border-radius:10px;padding:9px 12px;font-weight:700}button{cursor:pointer}#status{margin-top:10px;background:#fff;color:#333;border-radius:10px;padding:10px;font-size:12px}table{width:100%;border-collapse:collapse;min-width:950px;font-size:12px}th,td{padding:8px;border-bottom:1px solid #e5e7eb;text-align:center;white-space:nowrap}th{background:#eef1f4}.scroll{overflow:auto}.green{color:#16823b;font-weight:700}.red{color:#c62828;font-weight:700}.empty{text-align:center;padding:28px;color:#666}
</style></head><body><main class="wrap"><section class="top"><h1>🎯 داشبورد اختیار معامله — قالب ۱</h1><div class="sub">دو سررسید فعال • ۵ قرارداد برتر هر سررسید بر اساس ارزش معاملات روز • بروزرسانی هر ۳۰ ثانیه</div><div class="actions"><span id="clock" class="badge">—</span><button id="refresh">↻ بروزرسانی</button></div><div id="status">در حال دریافت داده…</div></section><div id="app"></div></main><script>
const $=x=>document.getElementById(x),fmt=x=>Number.isFinite(Number(x))?Number(x).toLocaleString('fa-IR'):'—';
function out(v){if(!Number.isFinite(Number(v)))return'—';return '<span class="'+(v>=0?'green':'red')+'">'+Number(v).toFixed(1)+'٪</span>'}
function calc(u,s,p,change){if(![u,s,p].every(Number.isFinite)||p<=0)return null;const t=u*(1+change/100);return((Math.max(t-s,0)-p)/p)*100}
function risk(u,s,p){if(![u,s,p].every(Number.isFinite)||u<=0||p<=0)return'🔴 بسیار زیاد';const d=Math.abs((s+p-u)/u*100);return d<=1?'🟢 کم':d<=2?'🟢🟡 متوسط':d<=3?'🟡 متوسط':d<=4?'🟠 زیاد':'🔴 بسیار زیاد'}
function render(rows){
 if(!rows.length){$('app').innerHTML='<section class="card empty">⚠️ داده زنده معتبر بازار فعلاً در دسترس نیست. هیچ عدد ساختگی نمایش داده نمی‌شود.</section>';return}
 const g={};for(const r of rows)(g[r.maturity]??=[]).push(r);const ms=Object.keys(g).sort().slice(0,2);
 let h='<section class="card"><h2>سررسیدهای فعال</h2><div class="note">ماه اول: 🟤 '+(ms[0]||'—')+' &nbsp; | &nbsp; ماه دوم: ⚫ '+(ms[1]||'—')+'</div></section>';
 ms.forEach((m,i)=>{const rs=g[m].sort((a,b)=>(b.dailyValue||0)-(a.dailyValue||0)).slice(0,5),c=i?'⚫':'🟤',base=rs.find(x=>Number.isFinite(x.underlying))?.underlying||0;
 h+='<section class="card"><h3>📊 جدول ۱ — مقایسه قراردادها</h3><div class="scroll"><table><thead><tr><th>نماد</th><th>قیمت پریمیوم</th><th>قیمت سهم پایه</th><th>اعمال</th><th>سر‌به‌به‌سر</th><th>ارزش معاملات روز</th><th>ریسک</th>'+[5,10,15,20,30,40,50].map(x=>'<th>'+x+'٪ = '+fmt(base*(1+x/100))+'</th>').join('')+'</tr></thead><tbody>';
 rs.forEach(r=>{const u=Number(r.underlying),s=Number(r.strike),p=Number(r.premium);h+='<tr><td>'+c+' '+r.symbol+'</td><td>'+fmt(p)+'</td><td>'+fmt(u)+'</td><td>'+fmt(s)+'</td><td>'+fmt(s+p)+'</td><td>'+fmt(r.dailyValue)+'</td><td>'+risk(u,s,p)+'</td>'+[5,10,15,20,30,40,50].map(x=>'<td>'+out(calc(u,s,p,x))+'</td>').join('')+'</tr>'});
 h+='</tbody></table></div></section><section class="card"><h3>📊 جدول ۲ — سناریوی نزولی</h3><div class="scroll"><table><thead><tr><th>نماد</th><th>سر‌به‌به‌سر</th>'+[-3,-6,-9].map(x=>'<th>'+Math.abs(x)+'٪ = '+fmt(base*(1+x/100))+'</th>').join('')+'<th>ریسک</th></tr></thead><tbody>';
 rs.forEach(r=>{const u=Number(r.underlying),s=Number(r.strike),p=Number(r.premium);h+='<tr><td>'+c+' '+r.symbol+'</td><td>'+fmt(s+p)+'</td>'+[-3,-6,-9].map(x=>'<td>'+out(calc(u,s,p,x))+'</td>').join('')+'<td>'+risk(u,s,p)+'</td></tr>'});
 h+='</tbody></table></div></section>'});
 h+='<section class="card"><h3>🔎 خلاصه ریسک</h3><div class="note">محاسبه فقط از داده معتبر دریافتی انجام می‌شود؛ در صورت نبود داده، عددی حدس زده نمی‌شود.</div></section>';
 $('app').innerHTML=h;
}
async function load(){ $('status').textContent='در حال دریافت آخرین داده معتبر…';try{const r=await fetch('/api/options',{cache:'no-store'}),j=await r.json();if(!r.ok)throw 0;render(j.data||[]);$('status').textContent='آخرین دریافت: '+new Date(j.updatedAt).toLocaleString('fa-IR')}catch(e){render([]);$('status').textContent='⚠️ منبع بازار فعلاً پاسخ معتبر نداد؛ عدد ساختگی نمایش داده نمی‌شود.'}}
function tick(){$('clock').textContent='آخرین بررسی: '+new Date().toLocaleTimeString('fa-IR')}document.getElementById('refresh').onclick=()=>{tick();load()};tick();load();setInterval(()=>{tick();load()},30000);
</script></body></html>`;
function n(v){const x=Number(v);return Number.isFinite(x)?x:null}
function norm(raw){const a=Array.isArray(raw)?raw:(raw?.data||raw?.Data||raw?.items||raw?.Items||raw?.result||raw?.Result||[]);if(!Array.isArray(a))return[];return a.map(o=>{const g=(...k)=>{for(const q of k)if(o?.[q]!=null)return o[q];return null};return{symbol:g('Symbol','symbol','InstrumentSymbol','instrumentSymbol','Name','name'),maturity:g('Maturity','maturity','ExerciseDate','exerciseDate','MaturityDate','maturityDate','Date','date'),premium:n(g('LastPrice','lastPrice','Price','price','LastTradedPrice','lastTradedPrice','PrcLast','Close','close')),underlying:n(g('UnderlyingPrice','underlyingPrice','BasePrice','basePrice','UnderlyingLastPrice','underlyingLastPrice')),strike:n(g('Strike','strike','ExercisePrice','exercisePrice','StrikePrice','strikePrice')),dailyValue:n(g('DailyValue','dailyValue','TradeValue','tradeValue','Value','value','VolumeValue','volumeValue'))}}).filter(x=>x.symbol&&x.maturity&&x.premium!=null&&x.strike!=null)}
async function get(u){const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(u,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json'}});if(!r.ok)throw 0;return await r.json()}finally{clearTimeout(t)}}
async function data(){for(const u of URLS)try{const x=norm(await get(u));if(x.length)return x}catch{}return[]}
http.createServer(async(q,s)=>{if(q.url==='/health'){s.writeHead(200,{'content-type':'application/json'});return s.end(JSON.stringify({ok:true}))}if(q.url==='/api/options'){const d=await data();s.writeHead(d.length?200:503,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});return s.end(JSON.stringify(d.length?{updatedAt:new Date().toISOString(),data:d}:{data:[],error:'market data unavailable'}))}s.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});s.end(page)}).listen(PORT,()=>console.log('listening '+PORT));